version: "3.8"

services:

  db:
    image: postgres:15
    container_name: taskplatform_db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: taskplatform_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    # "build: ." = zbuduj image z Dockerfile w bieżącym folderze
    container_name: taskplatform_app
    
    ports:
      - "8000:8000"

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    environment:
      # Uwaga: tu używamy nazw serwisów ("db", "redis") jako hostnames!
      # Docker Compose tworzy wewnętrzną sieć — serwisy widzą się po nazwie
      # "localhost" NIE zadziała — dla kontenera "app", baza to "db", nie "localhost"
      DATABASE_URL: postgresql://taskuser:taskpassword@db:5432/taskdb
      REDIS_URL: redis://redis:6379
      SECRET_KEY: 0jaInno0ZvFMzgBbpHqojej94uMaqMPX
      DEBUG: "True"
    
    depends_on:
      # "depends_on" = uruchom ten serwis dopiero gdy tamte są gotowe
      db:
        condition: service_healthy   # czekaj aż healthcheck przejdzie
      redis:
        condition: service_healthy
    
    # W trybie deweloperskim montujemy kod jako volumen
    # Zmiana w pliku .py jest od razu widoczna w kontenerze — bez rebuildu!
    volumes:
      - .:/app

    

    # ===== CELERY WORKER =====
  worker:
    build: .
    container_name: taskplatform_worker
    # Komenda uruchamiająca workera
    # -A app.workers.celery_app = "znajdź instancję Celery w tym module"
    # worker = tryb workera (wykonuje zadania)
    # --loglevel=info = pokazuj logi na poziomie INFO
    command: celery -A app.workers.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://taskuser:taskpassword@db:5432/taskdb
      REDIS_URL: redis://redis:6379
      SECRET_KEY: 0jaInno0ZvFMzgBbpHqojej94uMaqMPX
      DEBUG: "True"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  # ===== CELERY BEAT =====
  beat:
    build: .
    container_name: taskplatform_beat
    # beat = tryb schedulera (wysyła zadania cykliczne do kolejki)
    # --scheduler django_celery_beat.schedulers:DatabaseScheduler
    # na razie używamy domyślnego schedulera
    command: celery -A app.workers.celery_app beat --loglevel=info
    environment:
      DATABASE_URL: postgresql://taskuser:taskpassword@db:5432/taskdb
      REDIS_URL: redis://redis:6379
      SECRET_KEY: 0jaInno0ZvFMzgBbpHqojej94uMaqMPX
      DEBUG: "True"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  # ===== PROMETHEUS =====
  prometheus:
    image: prom/prometheus:latest
    container_name: taskplatform_prometheus
    ports:
      - "9090:9090"
    volumes:
      # montujemy nasz plik konfiguracyjny
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # prometheus musi startować po aplikacji
    depends_on:
      - app

  # ===== GRAFANA =====
  grafana:
    image: grafana/grafana:latest
    container_name: taskplatform_grafana
    ports:
      - "3000:3000"
    environment:
      # domyślne dane logowania do Grafany
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      # trwałe przechowywanie dashboardów i konfiguracji
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:    # ← nowy volumen